version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: stock-analysis-mongodb
    restart: unless-stopped
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
        - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - stock-analysis-network

volumes:
  mongodb_data:

networks:
  stock-analysis-network:
    driver: bridge
